// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqwvbvjwfmhhkqxdbuqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xd3Zidmp3Zm1oaGtxeGRidXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTY2OTUsImV4cCI6MjA2Mjk5MjY5NX0.kyxLn9YLl3yinBuQFJvqmxWxP1h08BMvP2P5CyD5A9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);